foodmatch/foodfinder/urls.py
from django.conf.urls import patterns, url
from foodfinder import views

urlpatterns = patterns('',
		url(r'^$', views.index, name='index'),
		url(r'^index/$', views.index, name='index'),
		url(r'^register/$', views.register, name='register'),
		url(r'^login/$', views.user_login, name='user_login'),
		url(r'^logout/$', views.user_logout, name='user_logout'),
		url(r'^home/$', views.home, name='home'),
		url(r'^settings/$', views.settings, name='settings'),
		url(r'^untitled/$', views.random, name='untitled'),
		)

foodmatch/foodmatch/urls.py
from django.conf.urls import patterns, include, url
from foodfinder import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'foodmatch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^foodfinder/', include('foodfinder.urls')),
    url(r'^$', views.redirection, name='redirection'),
)

foodmatch/foodfinder/models.py
from django.db import models
from django.contrib.auth.models import User
from preferences import Preferences
#from views import request_record

# Create your models here.


#class Dining_Hall(models.Model):

class Menu(models.Model):
	dining_hall = models.CharField(max_length=128)

class Food(models.Model):
	menu = models.ForeignKey(Menu)
	name = models.CharField(max_length=128)

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	phone = models.IntegerField(default=0)
	preferences = models.CharField(max_length=128)
	def __unicode__(self):
		return self.user.username

foodmatch/foodfinder/forms.py
from django import forms
from foodfinder.models import Food, Menu, UserProfile
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("phone", "preferences")

foodmatch/foodfinder/views.py
# Create your views here.
import os
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response
from foodfinder.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from foodfinder.models import UserProfile
from django.contrib.auth.models import User
from django import conf
from django.views.decorators.csrf import csrf_protect
from menu_parser import MenuParser
from preferences import Preferences
from django.core.context_processors import csrf

# file_ = open(os.path.join(settings.PROJECT_ROOT, 'menu.txt'))

def redirection(request):
	context = RequestContext(request)
	return HttpResponseRedirect('/foodfinder/index/')

def index(request):
	context = RequestContext(request)
	preference_list = UserProfile.objects
	all_entries = preference_list.all()
	x = []
	for entry in all_entries:
		y = entry.preferences
	return render_to_response('foodfinder/index.html', {'preference':y}, context)

request_record = 0

def random(request):
	context = RequestContext(request)
	return render_to_response('foodfinder/untitled.html', context)

def register(request):
	print("GOT HERE BITCHES")
	global request_record
	request_record = request
	context = RequestContext(request)
	c = {}
	c.update(csrf(request))
	registered = False
	if request.method == 'POST':
		print("GOT THE POST MANNNNNNNNN")
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			print("The form was uber valid")
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.phone = request.POST['phone']
			profile.save()
			registered = True
		else:
			print("Nah there were issues baby")
			print user_form.errors, profile_form.errors
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
	c['user_form'] = user_form
	c['profile_form'] = profile_form
	c['registered'] = registered
	return render_to_response('foodfinder/register.html', c,
            context)

def user_login(request):
	context = RequestContext(request)
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/foodfinder/home/')
			else:
				return HttpResponse('Your account was disabled. Bitch.')
		else:
			print "Invalid login details."
			return HttpResponse("Invalid login details supplied. Foiled you, wannabe hacker.")
	else:
		return render_to_response("foodfinder/login.html", {}, context)

def get_context_dict(request):
	u = User.objects.get(username=request.user)
	try:
		up = UserProfile.objects.get(user=u)
	except:
		up = None
	context_dict = {'user': u, 'userprofile': up}
	return context_dict;

@csrf_protect
@login_required
def home(request):
	context = RequestContext(request)
	context_dict = get_context_dict(request)

	menu_path = os.path.join(conf.settings.PROJECT_ROOT, 'menu.txt')
	menu = MenuParser(menu_path)
	menu = menu.parse_menu()
	preferences = context_dict['userprofile'].preferences
	preferences = Preferences.createFromString(preferences)
	matches = menu.match_with(preferences)
	html = ""
	for item in matches.get_items(): # TODO: make menu object iterable
		html += "<div style='margin-bottom: 4px; width: 400px; float left;'>"
		html += "<font style='text-decoration: underline;'>"+item.name+"</font><font color='black'> for "+item.meal+" @ "+item.location+"</font>"
		html += "</div>"
	context_dict['matches'] = html
	return render_to_response("foodfinder/home.html", context_dict, context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/foodfinder/')

@login_required
def settings(request):
	context = RequestContext(request)
	u = User.objects.get(username=request.user)
	try:
		up = UserProfile.objects.get(user=u)
	except:
		up = None
	context_dict = {'user': u, 'userprofile': up}
	if request.method == "POST":
		new_prefs = request.POST.get('preferences')
		up.preferences = new_prefs
		up.save()
		return HttpResponseRedirect('/foodfinder/home/')
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	#return render_to_response('foodfinder/settings.html', {'user_form': user_form, 'profile_form': profile_form}, context)
	return render_to_response("foodfinder/settings.html", get_context_dict(request), context)

foodmatch/templates/foodfinder/<!DOCTYPE html>.html
<!DOCTYPE html>

<html>
	<head>
		<title>Insert preferences here.</title>
	</head>
	<body>

		<form id="Preference form" method="post" action="/foodfinder/restricted/">{% csrf_token %}
			Preferences: <input type="text" name="username" value="" size="50" />
            
            <br />
            <input type="submit" value="submit" />
        </form>
	</body>
</html>

foodmatch/templates/foodfinder/home.html
<!DOCTYPE html>
{% extends 'foodfinder/index.html' %}

{% block body_block %}
<html>
	<head>
		<title>Hungry Bear - Home</title>
	</head>
	<body>
		<h1>Welcome to Hungry Bear</h1> 
		<a href="/foodfinder/settings/">Settings</a>&nbsp;&nbsp;<a href="/foodfinder/logout/">Logout</a><br /><br>
		<strong>This is you.</strong><br>
		Username: {{ user.username }}<br>
		Email: {{ user.email }}<br>
		Phone: {{ user.userprofile.phone }}<br><br>
		<strong>Your eating preferences.</strong>&nbsp;&nbsp;<a href='/foodfinder/settings/'>Change these</a><br />
		{{ user.userprofile.preferences }}<br><br>
		<!--<strong>Notify me via:</strong><br>
		Email, text<br><br>-->
		<strong>Your personal menu.</strong><br>
		{% autoescape off %}{{ matches }}{% endautoescape %}
		<br>
	</body>
</html>
{% endblock %}

foodmatch/templates/foodfinder/index.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
	<head>	
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <!-- Bootstrap -->
	    <link href="{% static "css/bootstrap-fluid-adj.css" %}" rel="stylesheet" type="text/css">
	    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen" type="text/css">
	    <link href="{% static "css/bootstrap-responsive.css" %}" rel="stylesheet" type="text/css">
	    <style type='text/css'>
	    	#main {
	    		margin: 0 auto;
	    		width: 500px;
	   			background-image: url('');
	    	}
	    	#main #buttons {
	    		width: 100%;
	    		text-align: left;
	    	}

	    	html, body {
	    		height: 100%;
	    	}

	    	body {  position: relative;}

			body:before {
			    content: "";
			    position: absolute;
			    top: 0;
			    bottom: 0;
			    left: 0;
			    right: 0;
			    z-index: 1;
			    background-image: url('http://upload.wikimedia.org/wikipedia/commons/7/7f/UCBerkeleyCampus.jpg');
			   	background-size: 100% auto;
			   opacity: 0.3;
			}

			#main {
			    position: relative; 
			    z-index: 2;
			}​
	    </style>
    <title> {% block title %} Hungry Bear - Eat Right. {% endblock %}</title>
	</head>
	<body>
		<div id='main'>
			{% block body_block %}
			<div>
				<h1>Welcome to Hungry Bear</h1>
				<p>Hungry? Just tell <b>Hungry Bear</b> what you like to eat, <br> and it'll notify you whenever Cal Dining is serving something you like!</p>
				<div id='buttons'>
	                <a href="/foodfinder/register/"><font>Register</font></a>&nbsp;&nbsp;&nbsp;&nbsp;
	                <a href="/foodfinder/login/"><font>Login</font></a>
	            </div>
	        </div>
	        {% endblock %}
	    </div>
		<script src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<footer>
    	<div class="container" style="margin: 0 auto; width: 500px; margin-top: 6px;">
        	<p><b>&copy; Hungry Bear 2013</b></p>
    	</div>
	</footer>
	</body>
</html>

foodmatch/templates/foodfinder/login.html
<!DOCTYPE html>
{% extends "foodfinder/index.html" %}

{% block body_block %}
<html>
    <head>
        <title>Hungry Bear - Login</title>
    </head>

    <body>
        <h1>Welcome to Hungry Bear</h1>
        <h3 style="text-decoration: underline;">Login to your account</h3>
        <form id="login_form" method="post" action="/foodfinder/login/" style="margin-bottom: 15px;">
            {% csrf_token %}
            <input type="text" name="username" value="" size="50" placeholder="username"/><br />
            <input type="password" name="password" value="" size="50" placeholder="************"/><br />
            <input type="submit" value="submit" />
        </form>
        <div id='buttons'>
            <a href="/foodfinder/index/"><font>Back to main page</font></a>
        </div>
    </body>
</html>
{% endblock %}

foodmatch/templates/foodfinder/register.html
<!DOCTYPE html>
{% extends 'foodfinder/index.html' %}

{% block body_block %}
<html>
    <head>
        <title>Hungry Bear - Register</title>
    </head>

    <body>

        <h1>Welcome to Hungry Bear</h1>
        <h3 style="text-decoration: underline;">Register for an account</h3>
        {% if registered %}
            <strong>Thanks for signing up!</strong><br>
            Go ahead and <a href="/foodfinder/login">login.</a><br />
        {% else %}
            <form id="user_form" method="post" action="/foodfinder/register/" enctype="multipart/form-data" style="margin-bottom: 15px;">
                {% csrf_token %}
                <p><input id="id_username" maxlength="30" name="username" type="text" placeholder="username" style="width: 265px;"/> <br></p>
                <p><input id="id_email" maxlength="75" name="email" type="text" placeholder="email@berkeley.edu" style="width: 265px;"/></p>
                <p><input id="id_password" name="password" type="password" placeholder="**********" style="width: 265px;"/></p>
                <p><input id="id_phone" name="phone" type="text" placeholder="5043368080" style="width: 265px;"/></p>
                <p><input id="id_preferences" maxlength="128" name="preferences" type="text" placeholder="nachos, tator tots, grilled cheese" style="width: 265px;"/></p>
                <!-- Provide a button to click to submit the form. -->
                <input type="submit" name="submit" value="Register" />
            </form>
        {% endif %}
        <div id='buttons'>
            <a href="/foodfinder/index/"><font>Back to main page</font></a>
        </div>
    </body>
</html>
{% endblock %}

foodmatch/templates/foodfinder/restricted1.html
<!DOCTYPE html>

<html>
	<head>
		<title>Insert preferences here.</title>
	</head>
	<body>
		<form id="Preference form" method="post" action="/foodfinder/restricted/">
            {{ field_area }}
            Edit Preferences: <input type="text" name="username" value="" size="50" />
            <br />
            <input type="submit" value="submit" />
        </form>
	</body>
</html>

foodmatch/templates/foodfinder/selection_page.html
<!DOCTYPE html>

<html>
	<head>
		{% if user.is_authenticated %}
		<h1>Rango says... hello {{ user.username }}!</h1>

		{% else %}
		<h1>Rango says... hello world!</h1>
		{% endif %}
	</head>
	<body>
		{% if user.is_authenticated %}
			<a href="/foodfinder/restricted/">Restricted Page</a><br />
			<a href="/foodfinder/logout/">Logout</a><br /> 
			<br />
			<br />
			
		<form>
            <input type="submit" value="Edit preferences"/> 
        
        </form>

		{% else %}
			<a href="/foodfinder/register/">Register Here</a><br />
			<a href="/foodfinder/login/">Login</a><br />
		{% endif %}
				
		<br />
		

	</body>
</html>

foodmatch/templates/foodfinder/settings.html
<!DOCTYPE html>
{% extends 'foodfinder/index.html' %}

{% block body_block %}
<html>
	<head>
		<title>Hungry Bear - Settings</title>
	</head>
	<body>
		<h1>Welcome, {{ user.username }}, to Hungry Bear</h1> 
		<a href="/foodfinder/home/">Home</a>&nbsp;&nbsp;<a href="/foodfinder/logout/">Logout</a><br /><br>
		<form method='post' action="/foodfinder/settings/">
			{% csrf_token %}
			<strong>Change your eating preferences if you like.</strong><br>
            <input type='text' name='preferences' id='preferences' style='width: 400px;' value='{{ user.userprofile.preferences }}'>
      		<input type='submit' value='Save changes'/>
		</form>
	</body>
</html>
{% endblock %}

foodmatch/templates/foodfinder/untitled.html
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Your Site</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL|default:"/s/"}}css/cupertino/jquery-ui-1.9.1.custom.min.css" rel="stylesheet">
    <link href="{{STATIC_URL|default:"/s/"}}css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      {% block css %}{% endblock %}
    </style>
    <link href="{{STATIC_URL|default:"/s/"}}css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
     -->
     <script src="{{STATIC_URL|default:"/s/"}}js/jquery-1.8.2.min.js"></script>
     <script type="text/javascript">
     {% block javascript %}
     $(function(){
     {% block jquery %}
     {% endblock %}
     });
     {% endblock %}
     </script>
     {% if not debug %}{% include "analytics.html" %}{% endif %}
  </head>

  <body>
{% comment %}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
{% endcomment %}
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a href="/"><img src="{{STATIC_URL|default:"/s/"}}img/logo1.png" /></a>
          {% if user.is_authenticated %}
          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>{{user.first_name}} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'accounts:overview' %}"><i class="icon-briefcase"></i>My Account</a></li>
                <li><a href="{% url 'accounts:signout' %}"><i class="icon-off"></i>Sign out</a></li>
                {% if user.is_staff %}
                <li class="divider"></li>
                <li class="nav-header">Administration</li>
                <li><a href="{% url 'admin:index' %}">Site Administration</a></li>
                <li><a href="{% url 'admin:app_list' 'accounts' %}">Accounts</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
          {% else %}
          <form class="navbar-form pull-right" action="{% url 'accounts:signin' %}" method="post">{% csrf_token %}
              <input class="span2" type="text" name="username" placeholder="Username">
              <input class="span2" type="password" name="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container">
      {% if messages %}
      <div class="row">
        <div class="span12">
          {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <strong>{{message.tags|title}}:</strong> {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% if debug %}
      <div class="alert"><strong>Running in DEBUG mode</strong></div>
      {% endif %}
{% block base_content %}
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>
{% endblock %}
      <hr>

      <footer>
        <p>&copy; Your Site 2012</p>
      </footer>

    </div> <!-- /container -->
    <script src="{{STATIC_URL|default:"/s/"}}js/jquery-ui-1.9.1.custom.min.js"></script>
    <script src="{{STATIC_URL|default:"/s/"}}js/bootstrap.min.js"></script>
    {% block extrafooter %}{% endblock %}
  </body>
</html>